name: Build Typst Docs

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**/*.typ"
  pull_request:
    paths:
      - "docs/**/*.typ"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      uses: actions/checkout@v4

      - name: Compile all Typst files in documentation/
        uses: lvignoli/typst-action@v1
        with:
          source_file: docs/*.typ

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: typst-docs
          path: docs/*.pdf
