name: Build Typst Docs

on:
  push:
    branches: [ main ]
    paths:
      # On surveille tout le dossier documentation et ses sous-dossiers (**)
      - "documentation/**/*.typ"
  pull_request:
    paths:
      - "documentation/**/*.typ"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Main Typst file
        uses: lvignoli/typst-action@v1
        with:
          # IMPORTANT : On ne compile QUE le fichier maître.
          # Il se chargera d'importer les chapitres et les utils.
          source_file: documentation/main.typ

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: typst-docs
          # Le PDF généré se trouvera à côté du fichier main.typ
          path: documentation/main.pdf
